version: '3.9'

services:
  db:
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

  api:
    command: npm run start:dev
    volumes:
      - ../server:/home/node/app
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - API_PORT

  client:
    command: npm run serve
    volumes:
      - ../client:/home/node/app
    ports:
      - ${CLIENT_PORT}:4200
    environment:
      - API_PORT
