version: '3.9'

services:
  db:
    ports:
      - ${POSTGRES_PORT}:5432

  api:
    command: npm run start:dev
    volumes:
      - ../server:/home/node/app
    ports:
      - ${API_PORT}:${API_PORT}
      - 5555:5555 # prisma studio
    environment:
      - API_PORT

  client:
    command: npm run serve
    volumes:
      - ../client:/home/node/app
    ports:
      - ${CLIENT_PORT}:4200
