version: '3.9'

services:
  db:
    container_name: ${DB_SERVICE_CONTAINER}
    domainname: ${DB_SERVICE_CONTAINER}
    image: postgres:15
    restart: always
    networks:
      - trello
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - db:/var/lib/postgresql/data

  api:
    container_name: ${API_SERVICE_CONTAINER}
    domainname: ${API_SERVICE_CONTAINER}
    image: node:18
    working_dir: /home/node/app
    user: node
    networks:
      - trello
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
      - POSTGRS_URL=${DB_SERVICE_CONTAINER}
      - CLIENT_PORT
    depends_on:
      - db

  client:
    container_name: ${CLIENT_SERVICE_CONTAINER}
    domainname: ${CLIENT_SERVICE_CONTAINER}
    image: node:18
    user: node
    working_dir: /home/node/app
    networks:
      - trello
    environment:
      - SERVER_URL=${API_SERVICE_CONTAINER}
    depends_on:
      - api

networks:
  trello:
    driver: bridge

volumes:
  db:
